import { FormEvent, useState } from "react";
import { Camera, MapPin, Mic, ShieldCheck } from "lucide-react";
import SEO from "@/components/SEO";

const initialForm = { agentName:"", agentPhone:"", agentAgency:"", ownerName:"", ownerPhone:"", propertyType:"Plot", purpose:"Sell", location:"", locality:"", area:"", expectedPrice:"", mapLink:"", notes:"", consent:false };

export default function AgentInventoryIntake(){
  const [form,setForm]=useState(initialForm);
  const [result,setResult]=useState("");
  const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setResult("");try{
    const payload={ownerName:form.ownerName,phone:form.ownerPhone,listingSource:"Agent-listed property",agentName:form.agentName,agentPhone:form.agentPhone,agentAgency:form.agentAgency,sellerRole:"Authorised seller / representative",propertyType:form.propertyType,purpose:form.purpose,location:form.location,locality:form.locality,area:form.area,expectedPrice:form.expectedPrice,notes:[form.notes,form.mapLink?`Map: ${form.mapLink}`:"",`STAGING AGENT INTAKE — ${form.agentName} (${form.agentPhone})`].filter(Boolean).join("\n"),consent:form.consent};
    const r=await fetch("/api/property-listings",{method:"POST",headers:{"Content-Type":"application/json","X-ARE-Inventory-Mode":"staging"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Submission failed");setResult(`Submitted for ARE verification. Reference: ${d.propertyId||"created"}`);setForm(initialForm);
  }catch(err){setResult(err instanceof Error?err.message:"Submission failed");}finally{setBusy(false)}};
  return <main className="min-h-screen bg-[#f7f9ff] px-4 py-8 text-slate-900"><SEO title="Agent Inventory Intake | Anantha Real Estate" description="Private staging intake for approved Anantha property sourcing partners." path="/agent-inventory" />
    <div className="mx-auto max-w-3xl"><div className="mb-6 rounded-3xl bg-gradient-to-r from-[#605e8a] to-[#5eb1e3] p-7 text-white"><p className="text-sm font-semibold opacity-80">ANANTHA REAL ESTATE · STAGING</p><h1 className="mt-2 text-3xl font-bold">Agent Inventory Intake</h1><p className="mt-3 opacity-90">Add a property from your phone. Every submission stays pending until ARE verifies it.</p></div>
    <form onSubmit={submit} className="space-y-5 rounded-3xl border bg-white p-6 shadow-sm">
      <section><h2 className="font-bold">1. Who is submitting?</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><input required placeholder="Agent name" value={form.agentName} onChange={e=>setForm({...form,agentName:e.target.value})} className="rounded-xl border p-3"/><input required type="tel" placeholder="Agent phone" value={form.agentPhone} onChange={e=>setForm({...form,agentPhone:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Agency / team" value={form.agentAgency} onChange={e=>setForm({...form,agentAgency:e.target.value})} className="rounded-xl border p-3 md:col-span-2"/></div></section>
      <section><h2 className="font-bold">2. Property</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><select value={form.propertyType} onChange={e=>setForm({...form,propertyType:e.target.value})} className="rounded-xl border p-3"><option>Plot</option><option>Agricultural land</option><option>House / Villa</option><option>Apartment</option><option>Commercial property</option><option>Industrial / Warehouse</option><option>Development land</option></select><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} className="rounded-xl border p-3"><option>Sell</option><option>Rent / Lease</option></select><input required placeholder="Village / area" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Landmark / locality" value={form.locality} onChange={e=>setForm({...form,locality:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Area / size" value={form.area} onChange={e=>setForm({...form,area:e.target.value})} className="rounded-xl border p-3"/><input placeholder="Expected price / rent" value={form.expectedPrice} onChange={e=>setForm({...form,expectedPrice:e.target.value})} className="rounded-xl border p-3"/></div></section>
      <section><h2 className="font-bold">3. Owner / source</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><input required placeholder="Owner / authorised seller" value={form.ownerName} onChange={e=>setForm({...form,ownerName:e.target.value})} className="rounded-xl border p-3"/><input required type="tel" placeholder="Owner phone" value={form.ownerPhone} onChange={e=>setForm({...form,ownerPhone:e.target.value})} className="rounded-xl border p-3"/></div></section>
      <section><h2 className="font-bold">4. Location & field notes</h2><div className="mt-3 space-y-3"><label className="flex items-center gap-2 text-sm font-semibold"><MapPin size={17}/> Google Maps/location link</label><input placeholder="Paste map pin/link" value={form.mapLink} onChange={e=>setForm({...form,mapLink:e.target.value})} className="w-full rounded-xl border p-3"/><textarea rows={5} placeholder="Speak/type rough property details here for now…" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="w-full rounded-xl border p-3"/><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-dashed p-4 text-center text-sm text-slate-500"><Camera className="mx-auto mb-2"/>Photo capture/upload is next in staging</div><div className="rounded-xl border border-dashed p-4 text-center text-sm text-slate-500"><Mic className="mx-auto mb-2"/>Voice-to-fields is next in staging</div></div></div></section>
      <label className="flex gap-3 rounded-xl bg-slate-50 p-4 text-sm"><input required type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I confirm I am authorised to share these property/contact details with Anantha for private verification and buyer matching.</span></label>
      <div className="flex gap-2 rounded-xl bg-[#f0efff] p-4 text-sm"><ShieldCheck className="shrink-0 text-[#605e8a]"/><p>This staging intake does not publish the property. ARE verification and publication remain separate controls.</p></div>{result&&<p className="rounded-xl border p-4 text-sm">{result}</p>}<button disabled={busy} className="w-full rounded-xl bg-slate-900 px-5 py-4 font-semibold text-white">{busy?"Submitting…":"Submit to staging inventory"}</button>
    </form></div></main>
}