import { ArrowRight, Building2, CalendarDays, Check, ChevronRight, Download, FileText, MapPin, Phone, Route, ShieldCheck, Sparkles, Trees } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { useLeadEnquiry } from "@/components/LeadEnquiry";
import "./centralworld.css";

const mediaBase="/projects/green-home/central%20world";
const hero=`${mediaBase}/central%20world%20entrance.jpeg`;
const launchPoster="/central-world-launch-2026.png.png";
const brochure=`${mediaBase}/Central%20World%20Brochure.pdf`;
const eastPlan=`${mediaBase}/521_CW_60x40_East%20facing%20Residence(op%202)%20central%20world%20house%20construction%20plan.pdf`;
const westPlan=`${mediaBase}/521_CW_60x40_West%20facing%20Residence(op%202)%20central%20world%20houes%20construction%20plan.pdf`;
const gallery=[
  [`${mediaBase}/central%20world%20entrance.jpeg`,"Central World entrance"],
  [`${mediaBase}/central%20world%20street%20view.jpeg`,"Internal street view"],
  [`${mediaBase}/central%20world%20street%20view%201.jpeg`,"Central World internal roads"],
  [`${mediaBase}/central%20world%20street%20view%202.jpeg`,"Project development"],
  [`${mediaBase}/central%20world%20office.jpeg`,"Central World office"],
  [`${mediaBase}/central%20world%20office%20view%202.png`,"Project office view"],
  [`${mediaBase}/central%20world%20night%20view%20entrance.png`,"Entrance night view"],
  [`${mediaBase}/central%20world%20street%20lamp.jpeg`,"Street infrastructure"],
];
const phone="+916302966604";
const facts=[["125 acres","Planned township"],["31,000 sq ft","Clubhouse"],["Kanaparthi Padu","Nellore"],["NUDA & RERA","Approval stated in project marketing"]];
const amenities=["Planned internal roads","Clubhouse and community spaces","Swimming pool","Gymnasium","Function hall","Coffee shop","Indoor games","Landscaped open spaces"];
const faqs=[
  ["Where is Central World located in Nellore?","Central World is marketed at Kanaparthi Padu, Nellore. Buyers can arrange a site visit through Anantha Real Estate to understand the approach road, surrounding development and available plot options."],
  ["Who is the developer of Central World Nellore?","Central World is a plotted development by Green Home Developers and is being presented to buyers by Anantha Real Estate for project information, availability and site-visit coordination."],
  ["How large is the Central World project?","Project marketing describes Central World as a 125-acre planned plotted township with a 31,000 sq ft clubhouse and community amenities."],
  ["Can I check current plot availability and price?","Yes. Availability, plot sizes and current commercial terms can change, so use the enquiry or site-visit option on this page to request the latest details from Anantha Real Estate."],
  ["How can I visit Central World?","Register through this page or call Anantha Real Estate. For the 11 October 2026 grand opening, visitors can register for launch-event site-visit coordination."],
];

export default function CentralWorld(){
  const {openLead}=useLeadEnquiry();
  const enquire=(intent:string)=>openLead("Central World Nellore",intent);
  const structuredData=[
    {"@type":"Product","name":"Central World Nellore Plots","description":"Premium plotted township at Kanaparthi Padu, Nellore by Green Home Developers.","brand":{"@type":"Brand","name":"Green Home Developers"},"category":"Residential plots in Nellore","url":"https://www.anantharealestate.in/centralworld"},
    {"@type":"Event","name":"Central World III Grand Opening","startDate":"2026-10-11T10:30:00+05:30","eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","eventStatus":"https://schema.org/EventScheduled","location":{"@type":"Place","name":"Central World","address":{"@type":"PostalAddress","addressLocality":"Kanaparthi Padu, Nellore","addressRegion":"Andhra Pradesh","addressCountry":"IN"}},"organizer":{"@type":"Organization","name":"Green Home Developers"},"description":"Central World III grand opening and project site visit on 11 October 2026. Anantha Real Estate is coordinating visitor registrations."},
    {"@type":"FAQPage","mainEntity":faqs.map(([q,a])=>({"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}}))}
  ];

  return <div className="central-world min-h-screen bg-[#f8faff] text-[#292947]">
    <SEO title="Central World Nellore Plots | Green Home Developers | Site Visit" description="Central World Nellore by Green Home Developers: see real project photos, brochure, premium residential plots at Kanaparthi Padu, amenities, approvals, availability and site visits. Register for the 11 Oct 2026 grand opening visit." path="/centralworld" image="https://www.anantharealestate.in/projects/green-home/central%20world/central%20world%20entrance.jpeg" structuredData={structuredData}/>
    <Navbar/>
    <main>
      <section className="bg-white px-4 pb-12 pt-32 sm:px-6 lg:pb-20 lg:pt-40"><div className="container mx-auto grid items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#5260aa]">Green Home Developers · Kanaparthi Padu · Nellore</p><h1 className="mt-5 font-display text-5xl font-bold leading-tight text-[#303058] sm:text-6xl lg:text-7xl">Central World Nellore.<br/><span className="cw-gradient-text">See the project. Then decide.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[#636780]">Explore Central World through real project photographs, project documents and an on-ground site visit. Compare location, amenities and available residential plots with Anantha Real Estate.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" className="cw-primary rounded-xl px-6 text-white" onClick={()=>enquire("Central World Site Visit")}>Book Central World site visit <ArrowRight size={18}/></Button><a href={brochure} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#cfd6ef] bg-white px-5 text-sm font-semibold text-[#303058]"><FileText size={17}/>View project brochure</a></div><p className="mt-6 flex items-center gap-2 text-sm text-[#636780]"><MapPin size={16}/>Kanaparthi Padu, Nellore, Andhra Pradesh</p></div><figure className="overflow-hidden rounded-3xl border bg-[#f0f3ff] shadow-xl"><img src={hero} alt="Central World entrance at Kanaparthi Padu Nellore" className="aspect-[3/2] w-full object-cover"/><figcaption className="bg-white p-4 text-xs text-[#636780]">Central World Nellore · Actual project entrance</figcaption></figure></div></section>

      <section className="bg-[#2f245d] py-12 text-white"><div className="container mx-auto grid items-center gap-8 px-4 lg:grid-cols-[.8fr_1.2fr]"><img src={launchPoster} alt="Central World III grand opening 11 October 2026 Nellore" className="w-full rounded-2xl shadow-2xl"/><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/65">Sunday · 11 October 2026 · 10:30 AM</p><h2 className="mt-4 font-display text-4xl font-bold sm:text-5xl">Central World III Grand Opening</h2><p className="mt-5 max-w-xl leading-7 text-white/80">Join the launch event, experience Central World on-ground and understand the project before making your property decision. Anantha Real Estate will coordinate registered visitors.</p><div className="mt-6 flex flex-wrap gap-3"><Button size="lg" className="bg-white text-[#303058] hover:bg-white/90" onClick={()=>enquire("11 Oct Launch Event Site Visit")}>Register for launch site visit <CalendarDays size={18}/></Button><a href={`tel:${phone}`} className="inline-flex min-h-11 items-center gap-2 rounded-md border border-white/30 px-5 text-sm font-semibold"><Phone size={17}/>Call +91 63029 66604</a></div></div></div></section>

      <section className="border-b bg-white py-10"><div className="container mx-auto grid px-4 md:grid-cols-2 lg:grid-cols-4">{facts.map(([v,l])=><article key={v} className="border-r px-5 py-5"><p className="font-display text-3xl font-bold text-[#303058]">{v}</p><p className="mt-2 text-sm text-[#646480]">{l}</p></article>)}</div></section>

      <section className="bg-white py-20"><div className="container mx-auto px-4"><div className="mb-10 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#5361ae]">Actual project gallery</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058] sm:text-5xl">See Central World before your visit.</h2><p className="mt-4 leading-7 text-[#636780]">Real photographs from the project help you understand the entrance, internal roads, infrastructure and current on-ground environment.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{gallery.map(([src,alt],i)=><figure key={src} className={`group overflow-hidden rounded-2xl bg-[#eef0f7] ${i===0||i===5?"sm:col-span-2":""}`}><img src={src} alt={alt} loading="lazy" className="h-64 w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><figcaption className="bg-white px-4 py-3 text-xs font-medium text-[#636780]">{alt}</figcaption></figure>)}</div></div></section>

      <section className="py-20 sm:py-28"><div className="container mx-auto grid items-center gap-12 px-4 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#5361ae]">Central World project details</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058] sm:text-5xl">Residential plots in Nellore within a large planned township.</h2><p className="mt-6 text-base leading-8 text-[#5c6078]">Central World is marketed as a 125-acre premium plotted township at Kanaparthi Padu. For buyers comparing plots for sale in Nellore, the project combines a planned layout, community facilities and access to a major clubhouse. Current plot inventory, dimensions and commercial terms should always be confirmed before making a decision.</p><button onClick={()=>enquire("Talk to Central World Property Advisor")} className="mt-8 inline-flex items-center gap-2 border-b-2 border-[#303058] pb-2 text-sm font-bold">Talk to a property advisor <ChevronRight size={17}/></button></div><div className="grid gap-px border bg-[#e3e5f2] sm:grid-cols-2">{[["125-acre scale","A large planned township setting.",Building2],["Community lifestyle","31,000 sq ft clubhouse and amenities.",Sparkles],["Kanaparthi Padu","Explore the location and surrounding development.",Trees],["Buyer assistance","Check inventory, availability and arrange a visit.",ShieldCheck]].map(([t,x,I]:any)=><article key={t} className="bg-[#f8faff] p-7"><I className="text-[#5361ae]"/><h3 className="mt-8 text-2xl font-bold">{t}</h3><p className="mt-3 text-sm text-[#636780]">{x}</p></article>)}</div></div></section>

      <section className="bg-[#eef0f8] py-20"><div className="container mx-auto px-4"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#5361ae]">Project documents</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058]">Brochure & sample home plans.</h2><p className="mt-5 leading-7 text-[#636780]">Review the official project brochure and sample 60×40 east- and west-facing residence plans uploaded for Central World. For current inventory and commercial terms, contact Anantha Real Estate.</p></div><div className="grid gap-3"><a href={brochure} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><span className="flex items-center gap-3 font-semibold"><FileText className="text-[#5361ae]"/>Central World Project Brochure</span><Download size={18}/></a><a href={eastPlan} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><span className="flex items-center gap-3 font-semibold"><FileText className="text-[#5361ae]"/>60×40 East-facing sample residence plan</span><ChevronRight size={18}/></a><a href={westPlan} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><span className="flex items-center gap-3 font-semibold"><FileText className="text-[#5361ae]"/>60×40 West-facing sample residence plan</span><ChevronRight size={18}/></a></div></div></div></section>

      <section className="bg-[#393967] py-20 text-white"><div className="container mx-auto grid gap-12 px-4 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ddecff]">Central World location</p><h2 className="mt-4 font-display text-4xl font-bold sm:text-6xl">Plots at Kanaparthi Padu, Nellore.</h2><p className="mt-6 text-white/75">A site visit is the best way to understand the approach road, surrounding development, layout and individual plot options. Anantha Real Estate can coordinate the visit and help you compare the available inventory.</p></div><div className="border border-white/20 p-7"><Route/><p className="mt-7 font-semibold">See Central World location, road access and community spaces in person.</p><button onClick={()=>enquire("Central World Location & Site Visit")} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#ddecff]">Plan your visit <ArrowRight size={17}/></button></div></div></section>

      <section className="bg-white py-20"><div className="container mx-auto px-4"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#5361ae]">Central World amenities</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058]">More than a residential plot.</h2></div><div className="grid sm:grid-cols-2">{amenities.map(x=><div key={x} className="flex items-center gap-3 border-b py-5 text-sm font-semibold"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#eef0ff]"><Check size={14}/></span>{x}</div>)}</div></div></div></section>

      <section className="bg-[#f0f3ff] py-16"><div className="container mx-auto grid items-center gap-10 px-4 lg:grid-cols-[1.3fr_.7fr]"><img src={`${mediaBase}/central%20world%20street%20view%201.jpeg`} alt="Central World Nellore internal road and project development" className="w-full rounded-2xl"/><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#5260aa]">Central World site visit</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058]">See the project before you decide.</h2><p className="mt-5 text-[#636780]">Explore the approach road, available plots, project development and community plan. Ask for the latest price and availability during your consultation.</p><button onClick={()=>enquire("Schedule Central World Site Visit")} className="mt-6 inline-flex items-center gap-2 font-semibold text-[#5260aa]">Arrange a site visit <ArrowRight size={17}/></button></div></div></section>

      <section className="bg-white py-20"><div className="container mx-auto max-w-4xl px-4"><p className="text-center text-xs font-bold uppercase tracking-[.2em] text-[#5361ae]">Central World Nellore FAQ</p><h2 className="mt-4 text-center font-display text-4xl font-bold text-[#303058]">Questions buyers ask before a site visit</h2><div className="mt-10 divide-y border-y">{faqs.map(([q,a])=><article key={q} className="py-6"><h3 className="text-lg font-bold text-[#303058]">{q}</h3><p className="mt-3 leading-7 text-[#636780]">{a}</p></article>)}</div></div></section>

      <section className="bg-[#ddecff] py-20"><div className="container mx-auto grid gap-10 px-4 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#485aaa]">Central World plots Nellore</p><h2 className="mt-4 font-display text-4xl font-bold text-[#303058] sm:text-6xl">Check availability. Visit the project. Decide with clarity.</h2><p className="mt-6 text-[#555978]">Request current Central World plot availability, project details or site-visit coordination from Anantha Real Estate.</p></div><div className="border border-[#cfd6ef] bg-[#f8faff] p-7"><p className="text-sm font-bold">Speak to Anantha Real Estate</p><a href={`tel:${phone}`} className="mt-5 flex items-center gap-3 text-xl font-bold"><Phone size={20}/>+91 63029 66604</a><div className="mt-7 grid gap-3"><Button className="rounded-none bg-[#303058] py-6 text-white" onClick={()=>enquire("Central World Site Visit")}>Book site visit <ArrowRight size={18}/></Button><Button variant="outline" className="rounded-none py-6" onClick={()=>enquire("Central World Price & Availability")}>Check price & availability</Button></div></div></div></section>
    </main>
    <Footer/>
  </div>;
}
