import { ArrowRight, Building2, Factory, Landmark, Store, Warehouse } from "lucide-react";
import { Link } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import PropertyListingCard from "@/components/PropertyListingCard";
import { usePublicProperties } from "@/hooks/usePublicProperties";
import { stockImages } from "@/data/stockImages";

const types = [{ icon: Building2, title: "Office spaces", text: "Space for teams, practices and growing businesses." }, { icon: Store, title: "Retail", text: "Street-facing and customer-focused opportunities." }, { icon: Warehouse, title: "Warehouses", text: "Storage and logistics requirements." }, { icon: Factory, title: "Industrial", text: "Operational sites and industrial requirements." }, { icon: Landmark, title: "Commercial land", text: "Land with a business use case in mind." }];
const CommercialsPage = () => {
  const { properties, loading, error } = usePublicProperties();
  const opportunities = properties.filter((property) => property.type === "commercial" && property.status !== "unavailable");
  return <div className="min-h-screen bg-[#fafafa] text-slate-950"><SEO title="Commercial Real Estate in Nellore | Anantha Real Estate" description="Commercial property support for office, retail, warehouse, industrial and commercial land requirements in Nellore." path="/commercials"/><Navbar/><main>
    <section className="pt-28 md:pt-36"><div className="container mx-auto grid gap-8 px-4 md:grid-cols-[1.05fr_.95fr]"><div className="flex flex-col justify-end pb-10"><p className="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">Anantha Commercials</p><h1 className="mt-5 font-display text-5xl font-semibold leading-[.98] md:text-7xl">Planning your next business move in Nellore?</h1><p className="mt-6 max-w-xl leading-relaxed text-slate-600">Find a commercial space with clear local context and guidance for owners, occupiers and investors.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="#opportunities" className="bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Browse opportunities</Link><Link to="/contact?project=commercial-requirement" className="border border-slate-950 px-5 py-3 text-sm font-semibold">Talk to an advisor</Link></div></div><img src={stockImages.commercial} alt="Modern commercial building" className="h-[360px] w-full object-cover md:h-[560px]"/></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="container mx-auto grid gap-3 px-4 py-5 md:grid-cols-4"><input aria-label="Business requirement" placeholder="What space do you need?" className="h-12 border border-slate-300 px-4 text-sm outline-none focus:border-slate-950"/><input aria-label="Preferred location" placeholder="Preferred location" className="h-12 border border-slate-300 px-4 text-sm outline-none focus:border-slate-950"/><select aria-label="Property type" className="h-12 border border-slate-300 bg-white px-4 text-sm"><option>All commercial types</option><option>Office</option><option>Retail</option><option>Warehouse</option></select><Link to="/contact?project=commercial-requirement" className="flex h-12 items-center justify-center bg-slate-950 text-sm font-semibold text-white">Send requirement</Link></div></section>
    <section className="container mx-auto px-4 py-16 md:py-24"><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Find the right format</p><h2 className="mt-3 font-display text-4xl font-semibold md:text-5xl">Business spaces by need.</h2><div className="mt-9 grid gap-px border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{types.map(({ icon: Icon, title, text }) => <div key={title} className="bg-white p-6"><Icon size={23}/><h3 className="mt-8 font-display text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{text}</p></div>)}</div></section>
    <section id="opportunities" className="border-y border-slate-200 bg-[#f4f4f2] py-16 md:py-24"><div className="container mx-auto px-4"><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Featured opportunities</p><div className="mt-3 flex items-end justify-between gap-6"><h2 className="font-display text-4xl font-semibold md:text-5xl">Commercial inventory.</h2><Link to="/properties/commercial" className="hidden items-center gap-2 text-sm font-semibold md:inline-flex">View all property <ArrowRight size={16}/></Link></div>{loading ? <p className="mt-9 border border-slate-200 bg-white p-8 text-slate-600">Loading available property…</p> : error ? <p className="mt-9 border border-slate-200 bg-white p-8 text-slate-600">{error}</p> : opportunities.length ? <div className="mt-9 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{opportunities.slice(0, 3).map((property) => <PropertyListingCard key={property.slug} property={property}/>)}</div> : <div className="mt-9 border border-slate-200 bg-white p-8"><h3 className="font-display text-2xl font-semibold">Tell us what you need.</h3><p className="mt-3 max-w-xl text-slate-600">Public commercial listings are limited at the moment. Share your location and space requirement and the team can guide your next step.</p><Link to="/contact?project=commercial-requirement" className="mt-6 inline-flex items-center gap-2 bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Discuss a requirement <ArrowRight size={16}/></Link></div>}</div></section>
    <section className="container mx-auto grid gap-8 px-4 py-16 md:grid-cols-2 md:py-24"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">For every side of the transaction</p><h2 className="mt-3 font-display text-4xl font-semibold">Commercial guidance that starts with the decision.</h2></div><div className="grid gap-4"><article className="border-t border-slate-300 pt-4"><h3 className="font-semibold">For businesses</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Shortlist locations and formats around the way your business operates.</p></article><article className="border-t border-slate-300 pt-4"><h3 className="font-semibold">For owners and developers</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Present a commercial opportunity with a clear enquiry path and local support.</p></article><article className="border-t border-slate-300 pt-4"><h3 className="font-semibold">For investors</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Discuss property requirements and verification steps before moving forward.</p></article></div></section>
    <section className="bg-slate-950 py-16 text-white"><div className="container mx-auto grid gap-8 px-4 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/55">Commercial property support</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-semibold">Let’s make your next business location a considered move.</h2></div><Link to="/contact?project=commercial-requirement" className="inline-flex w-fit items-center gap-2 border border-white px-5 py-3 text-sm font-semibold hover:bg-white hover:text-slate-950">Start a conversation <ArrowRight size={16}/></Link></div></section>
  </main><Footer/></div>;
};
export default CommercialsPage;
