import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { CalendarPlus, CheckCircle2, ChevronRight, ClipboardList, Mail, MessageCircle, Phone, Search, SlidersHorizontal, UserRound } from "lucide-react";

type Enquiry = Record<string, any>;
type Visit = Record<string, any>;
const stages = ["NEW", "CONTACTED", "QUALIFIED", "NOT_QUALIFIED", "SITE_VISIT", "NEGOTIATION", "CLOSED", "LOST"];
const stageLabel = (value = "") => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase());
const date = (value?: string) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded";
const badge = (value = "") => value === "NEW" ? "bg-amber-50 text-amber-800" : ["CLOSED", "COMPLETED", "CONFIRMED"].includes(value) ? "bg-emerald-50 text-emerald-800" : ["LOST", "NOT_QUALIFIED", "CANCELLED", "NO_SHOW"].includes(value) ? "bg-rose-50 text-rose-700" : "bg-sky-50 text-sky-800";

export default function EnquiryAdmin() {
  const [items, setItems] = useState<Enquiry[]>([]), [visits, setVisits] = useState<Visit[]>([]), [csrf, setCsrf] = useState(""), [email, setEmail] = useState(""), [error, setError] = useState("");
  const [selected, setSelected] = useState<Enquiry | null>(null), [status, setStatus] = useState("NEW"), [notes, setNotes] = useState(""), [when, setWhen] = useState(""), [filter, setFilter] = useState("ACTIVE"), [query, setQuery] = useState(""), [busy, setBusy] = useState(false);

  async function load() {
    try {
      const response = await fetch("/api/enquiry-admin", { cache: "no-store" });
      const data = await response.json();
      if (response.status === 401) { setEmail(""); return; }
      if (!response.ok) throw new Error(data.error || "Could not load enquiries.");
      setItems(data.enquiries || []); setVisits(data.visits || []); setCsrf(data.csrf || ""); setEmail(data.email || "");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load enquiries."); }
  }
  useEffect(() => { void load(); }, []);

  function open(enquiry: Enquiry) { setSelected(enquiry); setStatus(enquiry.status || "NEW"); setNotes(enquiry.admin_notes || ""); setWhen(""); }
  async function post(body: Record<string, unknown>, keepOpen = false) {
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/enquiry-admin", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify(body) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Update failed.");
      if (!keepOpen) { setSelected(null); setNotes(""); setWhen(""); }
      await load();
      if (keepOpen && selected) setSelected({ ...selected, status: String(body.status || selected.status), admin_notes: String(body.notes || selected.admin_notes || "") });
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Update failed."); }
    finally { setBusy(false); }
  }

  const counts = useMemo(() => ({ active: items.filter(item => !["CLOSED", "LOST", "NOT_QUALIFIED"].includes(item.status)).length, new: items.filter(item => item.status === "NEW").length, qualified: items.filter(item => ["QUALIFIED", "SITE_VISIT", "NEGOTIATION"].includes(item.status)).length, visits: visits.filter(visit => ["SCHEDULED", "CONFIRMED", "RESCHEDULED"].includes(visit.status)).length }), [items, visits]);
  const filtered = useMemo(() => items.filter(item => {
    const matchesFilter = filter === "ACTIVE" ? !["CLOSED", "LOST", "NOT_QUALIFIED"].includes(item.status) : filter === "VISITS" ? item.status === "SITE_VISIT" : filter === "ALL" ? true : item.status === filter;
    return matchesFilter && Object.values(item).join(" ").toLowerCase().includes(query.trim().toLowerCase());
  }), [items, filter, query]);
  const currentVisits = selected ? visits.filter(visit => visit.enquiry_ref === selected.enquiry_ref) : [];

  if (!email) return <main className="grid min-h-screen place-items-center bg-slate-950 p-6 text-white"><Helmet><title>Enquiry Operations | Anantha</title><meta name="robots" content="noindex,nofollow"/></Helmet><section className="w-full max-w-md border border-white/15 bg-white/5 p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-200">Anantha Real Estate</p><h1 className="mt-3 text-3xl font-bold">Enquiry operations</h1><p className="mt-3 text-sm leading-6 text-white/70">Sign in to qualify buyer requirements and schedule site visits.</p><a href="/admin/login" className="mt-7 inline-flex bg-white px-5 py-3 text-sm font-semibold text-slate-950">Admin sign in</a>{error && <p className="mt-4 text-sm text-rose-300">{error}</p>}</section></main>;

  return <main className="min-h-screen bg-[#f5f7f8] text-slate-900"><Helmet><title>Enquiry Operations | Anantha</title><meta name="robots" content="noindex,nofollow"/></Helmet><div className="mx-auto max-w-[1500px] p-4 md:p-7"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0f7b74]">Anantha Real Estate · CRM</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Enquiry pipeline</h1><p className="mt-2 text-sm text-slate-600">Work each buyer from first contact through visit, negotiation and closure.</p></div><a href="/admin/crm" className="inline-flex items-center gap-2 border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Open CRM <ChevronRight size={16}/></a></header>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[counts.active, "Active enquiries", "Needs a next step"], [counts.new, "New leads", "Contact first"], [counts.qualified, "Qualified buyers", "Move to visit or deal"], [counts.visits, "Visits in progress", "Confirm attendance"]].map(([value, label, hint]) => <article key={String(label)} className="border border-slate-200 bg-white p-5"><p className="text-3xl font-bold">{value}</p><p className="mt-2 font-semibold">{label}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></article>)}</section>
  {error && <p className="mt-5 border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
  <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(360px,.9fr)_minmax(460px,1.1fr)]"><section className="min-w-0 border border-slate-200 bg-white"><div className="border-b border-slate-200 p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Work queue</h2><span className="text-xs text-slate-500">{filtered.length} records</span></div><div className="relative mt-4"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name, phone or requirement" className="h-10 w-full border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-[#0f7b74]"/></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{[["ACTIVE", "Active"], ["NEW", "New"], ["CONTACTED", "Contacted"], ["QUALIFIED", "Qualified"], ["VISITS", "Visits"], ["NEGOTIATION", "Negotiation"], ["ALL", "All"]].map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className={`shrink-0 border px-3 py-1.5 text-xs font-semibold ${filter === key ? "border-[#0f7b74] bg-[#0f7b74] text-white" : "border-slate-200 bg-white text-slate-600"}`}>{label}</button>)}</div></div>
  <div className="max-h-[660px] overflow-y-auto">{filtered.map(enquiry => <button key={enquiry.enquiry_ref} onClick={() => open(enquiry)} className={`block w-full border-b border-slate-100 p-5 text-left hover:bg-slate-50 ${selected?.enquiry_ref === enquiry.enquiry_ref ? "border-l-4 border-l-[#0f7b74] bg-teal-50/40" : ""}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{enquiry.name}</p><p className="mt-1 text-sm text-slate-600">{enquiry.property_type || "Property requirement"} · {enquiry.location || "Location to qualify"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge(enquiry.status)}`}>{stageLabel(enquiry.status)}</span></div><div className="mt-3 flex items-center justify-between gap-3 text-xs text-slate-500"><span>{enquiry.phone}</span><span>{date(enquiry.updated_at || enquiry.created_at)}</span></div></button>)}{!filtered.length && <div className="p-10 text-center"><ClipboardList className="mx-auto text-slate-300" size={28}/><p className="mt-3 text-sm text-slate-500">No enquiries in this queue.</p></div>}</div></section>
  <section className="min-h-[620px] border border-slate-200 bg-white p-5 md:p-7">{selected ? <><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0f7b74]">{selected.enquiry_ref}</p><h2 className="mt-2 text-2xl font-bold">{selected.name}</h2><p className="mt-1 text-sm text-slate-600">{selected.property_type || "Property requirement"} · {selected.location || "Location to confirm"}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${badge(status)}`}>{stageLabel(status)}</span></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2"><a href={`tel:${selected.phone}`} className="inline-flex items-center gap-2 border border-slate-200 p-3 text-sm font-semibold hover:border-[#0f7b74]"><Phone size={16} className="text-[#0f7b74]"/>Call {selected.phone}</a><a href={`https://wa.me/${String(selected.phone).replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-slate-200 p-3 text-sm font-semibold hover:border-[#0f7b74]"><MessageCircle size={16} className="text-[#0f7b74]"/>WhatsApp</a>{selected.email && <a href={`mailto:${selected.email}`} className="inline-flex items-center gap-2 border border-slate-200 p-3 text-sm font-semibold hover:border-[#0f7b74]"><Mail size={16} className="text-[#0f7b74]"/>Email buyer</a>}<span className="inline-flex items-center gap-2 border border-slate-200 p-3 text-sm text-slate-600"><UserRound size={16}/>Website enquiry</span></div>
  <div className="mt-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Buyer requirement</p><p className="mt-2 bg-slate-50 p-4 text-sm leading-6 text-slate-700">{selected.requirement || "No buyer requirement was submitted. Call to qualify budget, preferred locality, property type and timeline."}</p></div>
  <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Pipeline stage<select value={status} onChange={event => setStatus(event.target.value)} className="mt-2 h-11 w-full border border-slate-200 bg-white px-3 text-sm font-medium outline-none focus:border-[#0f7b74]">{stages.map(stage => <option key={stage}>{stage}</option>)}</select></label><label className="text-sm font-semibold">Internal notes<textarea value={notes} onChange={event => setNotes(event.target.value)} rows={3} placeholder="Record contact outcome, budget, timeline or next step" className="mt-2 w-full border border-slate-200 p-3 text-sm font-normal outline-none focus:border-[#0f7b74]"/></label></div>
  <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void post({ action: "STATUS", enquiryRef: selected.enquiry_ref, status, notes }, true)} className="inline-flex items-center gap-2 bg-[#0f7b74] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={16}/>Save update</button>{status === "NEW" && <button disabled={busy} onClick={() => { setStatus("CONTACTED"); void post({ action: "STATUS", enquiryRef: selected.enquiry_ref, status: "CONTACTED", notes }, true); }} className="border border-slate-300 px-4 py-2.5 text-sm font-semibold">Mark contacted</button>}{status === "CONTACTED" && <button disabled={busy} onClick={() => { setStatus("QUALIFIED"); void post({ action: "STATUS", enquiryRef: selected.enquiry_ref, status: "QUALIFIED", notes }, true); }} className="border border-slate-300 px-4 py-2.5 text-sm font-semibold">Qualify buyer</button>}</div>
  <div className="mt-8 border-t border-slate-200 pt-6"><div className="flex items-center gap-2"><CalendarPlus size={18} className="text-[#0f7b74]"/><h3 className="font-bold">Site visit</h3></div>{currentVisits.map(visit => <article key={visit.visit_ref} className="mt-3 border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{date(visit.scheduled_at)}</p><p className="mt-1 text-xs text-slate-500">{visit.notes || "No visit notes"}</p></div><select disabled={busy} defaultValue={visit.status} onChange={event => void post({ action: "VISIT_STATUS", enquiryRef: selected.enquiry_ref, visitRef: visit.visit_ref, visitStatus: event.target.value, notes }, true)} className="border border-slate-200 bg-white px-3 py-2 text-xs font-bold">{["SCHEDULED", "CONFIRMED", "COMPLETED", "RESCHEDULED", "CANCELLED", "NO_SHOW"].map(value => <option key={value}>{value}</option>)}</select></div></article>)}<div className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="datetime-local" value={when} onChange={event => setWhen(event.target.value)} className="h-11 flex-1 border border-slate-200 px-3 text-sm outline-none focus:border-[#0f7b74]"/><button disabled={busy || !when} onClick={() => void post({ action: "SITE_VISIT", enquiryRef: selected.enquiry_ref, scheduledAt: when, notes }, true)} className="inline-flex items-center justify-center gap-2 border border-[#0f7b74] px-4 py-2.5 text-sm font-bold text-[#0f7b74] disabled:opacity-50"><CalendarPlus size={16}/>Schedule visit</button></div></div></> : <div className="grid min-h-[540px] place-items-center text-center"><div><SlidersHorizontal className="mx-auto text-slate-300" size={34}/><h2 className="mt-4 text-xl font-bold">Choose an enquiry</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">Review the buyer’s requirement, record the outcome and make the next workflow step from one place.</p></div></div>}</section></div></div></main>;
}
