import { createHmac,timingSafeEqual } from "node:crypto";
const SESSION="__Host-property-admin";const send=(res,s,b)=>{res.statusCode=s;res.setHeader("Cache-Control","no-store");res.setHeader("Content-Type","application/json; charset=utf-8");res.end(JSON.stringify(b));};
const equal=(a,b)=>{const aa=Buffer.from(String(a)),bb=Buffer.from(String(b));return aa.length===bb.length&&timingSafeEqual(aa,bb)};
const cookie=(req,n)=>(req.headers.cookie||"").split(";").map(s=>s.trim()).find(s=>s.startsWith(n+"="))?.slice(n.length+1);
const emails=()=>String(process.env.PROPERTY_ADMIN_EMAILS||process.env.GBP_ADMIN_EMAILS||"info@anantharealestate.in").split(",").map(s=>s.trim().toLowerCase()).filter(Boolean);
const secret=()=>String(process.env.PROPERTY_ADMIN_SESSION_SECRET||process.env.PROPERTY_GOOGLE_CLIENT_SECRET||process.env.GBP_GOOGLE_CLIENT_SECRET||"");
const origin=()=>String(process.env.PROPERTY_ADMIN_ORIGIN||process.env.GBP_APP_ORIGIN||"https://www.anantharealestate.in").replace(/\/$/,"");
function admin(req){const t=cookie(req,SESSION),s=secret();if(!t||s.length<16)return null;const [body,sig]=String(t).split(".");if(!body||!sig)return null;const exp=createHmac("sha256",s).update(body).digest("base64url");if(!equal(sig,exp))return null;try{const x=JSON.parse(Buffer.from(body,"base64url").toString("utf8"));return x?.email&&x?.csrf&&x?.exp>Date.now()&&emails().includes(String(x.email).toLowerCase())?x:null}catch{return null}}
const db=()=>process.env.ANANTHA_DATABASE_URL||process.env.POSTGRES_URL||process.env.DATABASE_URL||"";
async function schema(sql){await sql`CREATE TABLE IF NOT EXISTS enquiries(id BIGSERIAL PRIMARY KEY,enquiry_ref TEXT UNIQUE NOT NULL,property_public_id TEXT,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,requirement TEXT,source TEXT NOT NULL DEFAULT 'website',status TEXT NOT NULL DEFAULT 'NEW',consent BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`ALTER TABLE enquiries ADD COLUMN IF NOT EXISTS requirement TEXT`;await sql`ALTER TABLE enquiries ADD COLUMN IF NOT EXISTS admin_notes TEXT`;await sql`ALTER TABLE enquiries ADD COLUMN IF NOT EXISTS qualified_at TIMESTAMPTZ`;await sql`CREATE TABLE IF NOT EXISTS site_visits(id BIGSERIAL PRIMARY KEY,visit_ref TEXT UNIQUE NOT NULL,enquiry_ref TEXT,property_public_id TEXT,scheduled_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'SCHEDULED',notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;}
export default async function handler(req,res){try{if(!db())return send(res,503,{error:"Database is not configured."});const s=admin(req);if(!s)return send(res,401,{error:"Administrator SSO sign-in required."});const {neon}=await import("@neondatabase/serverless");const sql=neon(db());await schema(sql);
if(req.method==="GET"){const rows=await sql`SELECT e.*,p.property_type,p.location FROM enquiries e LEFT JOIN property_listings p ON p.public_id=e.property_public_id ORDER BY e.created_at DESC LIMIT 500`;const visits=await sql`SELECT * FROM site_visits ORDER BY scheduled_at DESC NULLS LAST,created_at DESC LIMIT 500`;return send(res,200,{email:s.email,csrf:s.csrf,enquiries:rows,visits});}
if(req.method!=="POST"){res.setHeader("Allow","GET, POST");return send(res,405,{error:"Method not allowed."});}if(req.headers.origin!==origin()||!equal(req.headers["x-csrf-token"],s.csrf))return send(res,403,{error:"Request verification failed."});
const b=req.body||{},action=String(b.action||"").toUpperCase(),ref=String(b.enquiryRef||"").trim(),notes=String(b.notes||"").trim().slice(0,1500);if(!ref)return send(res,400,{error:"Enquiry reference required."});
if(action==="STATUS"){const status=String(b.status||"").toUpperCase();if(!["NEW","CONTACTED","QUALIFIED","NOT_QUALIFIED","SITE_VISIT","NEGOTIATION","CLOSED","LOST"].includes(status))return send(res,400,{error:"Invalid enquiry status."});const r=await sql`UPDATE enquiries SET status=${status},admin_notes=${notes},qualified_at=CASE WHEN ${status}='QUALIFIED' THEN COALESCE(qualified_at,NOW()) ELSE qualified_at END,updated_at=NOW() WHERE enquiry_ref=${ref} RETURNING *`;if(!r.length)return send(res,404,{error:"Enquiry not found."});return send(res,200,{ok:true,enquiry:r[0]});}
if(action==="VISIT_STATUS"){const vr=String(b.visitRef||"").trim(),vs=String(b.visitStatus||"").toUpperCase();if(!["SCHEDULED","CONFIRMED","COMPLETED","CANCELLED","NO_SHOW","RESCHEDULED"].includes(vs))return send(res,400,{error:"Invalid visit status."});const v=await sql`UPDATE site_visits SET status=${vs},notes=${notes},updated_at=NOW() WHERE visit_ref=${vr} RETURNING *`;if(!v.length)return send(res,404,{error:"Site visit not found."});return send(res,200,{ok:true,visit:v[0]});}
if(action==="SITE_VISIT"){const scheduled=String(b.scheduledAt||"").trim();if(!scheduled)return send(res,400,{error:"Site visit date and time required."});const e=await sql`SELECT enquiry_ref,property_public_id FROM enquiries WHERE enquiry_ref=${ref} LIMIT 1`;if(!e.length)return send(res,404,{error:"Enquiry not found."});const vr=`VIS-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const v=await sql`INSERT INTO site_visits(visit_ref,enquiry_ref,property_public_id,scheduled_at,notes) VALUES(${vr},${ref},${e[0].property_public_id},${scheduled}::timestamptz,${notes}) RETURNING *`;await sql`UPDATE enquiries SET status='SITE_VISIT',updated_at=NOW() WHERE enquiry_ref=${ref}`;return send(res,201,{ok:true,visit:v[0]});}
return send(res,400,{error:"Invalid action."});}catch(e){console.error("enquiry-admin error",e);return send(res,500,{error:"Could not process enquiry operations."});}}
