import {createHmac,randomBytes,timingSafeEqual,scryptSync} from "node:crypto";
const COOKIE="__Host-property-admin",MAX=8*60*60;
const send=(r,s,b)=>{r.statusCode=s;r.setHeader("Cache-Control","no-store");r.setHeader("Content-Type","application/json; charset=utf-8");r.end(JSON.stringify(b))};
const eq=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)};
const cookie=(r,n)=>(r.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(n+"="))?.slice(n.length+1);
const cfg=()=>{const email=String(process.env.PROPERTY_ADMIN_EMAIL||"shashankjanapati@gmail.com").trim().toLowerCase(),hash=String(process.env.PROPERTY_ADMIN_PASSWORD_HASH||"").trim(),secret=String(process.env.PROPERTY_ADMIN_SESSION_SECRET||"").trim(),origin=String(process.env.PROPERTY_ADMIN_ORIGIN||"https://www.anantharealestate.in").replace(/\/$/,"");return hash&&secret.length>=32?{email,hash,secret,origin}:null};
const sign=(p,s)=>{const b=Buffer.from(JSON.stringify(p)).toString("base64url");return b+"."+createHmac("sha256",s).update(b).digest("base64url")};
const verify=(t,s)=>{if(!t)return null;const [b,g]=String(t).split(".");if(!b||!g||!eq(g,createHmac("sha256",s).update(b).digest("base64url")))return null;try{return JSON.parse(Buffer.from(b,"base64url").toString("utf8"))}catch{return null}};
const set=(r,v,age)=>r.setHeader("Set-Cookie",`${COOKIE}=${v}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`);
const passwordOK=(password,stored)=>{const [alg,salt,key]=stored.split("$");if(alg!=="scrypt"||!salt||!key)return false;const got=scryptSync(String(password),salt,64).toString("hex");return eq(got,key)};
export default async function handler(req,res){res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");const c=cfg();if(!c)return send(res,503,{error:"Admin password login is not configured yet."});const q=new URL(req.url,c.origin).searchParams,action=q.get("action")||"session";
if(action==="login"){if(req.method!=="POST")return send(res,405,{error:"Method not allowed."});if(req.headers.origin!==c.origin)return send(res,403,{error:"Invalid request origin."});const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!eq(email,c.email)||!passwordOK(password,c.hash))return send(res,401,{error:"Invalid email or password."});const session={email:c.email,csrf:randomBytes(24).toString("base64url"),exp:Date.now()+MAX*1000};set(res,sign(session,c.secret),MAX);return send(res,200,{ok:true,email:c.email,csrf:session.csrf});}
if(action==="logout"){if(req.method!=="POST")return send(res,405,{error:"Method not allowed."});if(req.headers.origin!==c.origin)return send(res,403,{error:"Invalid request origin."});set(res,"",0);return send(res,200,{ok:true});}
if(req.method!=="GET")return send(res,405,{error:"Method not allowed."});const s=verify(cookie(req,COOKIE),c.secret);if(!s||s.exp<Date.now()||!eq(s.email,c.email))return send(res,401,{error:"Administrator login required."});return send(res,200,{ok:true,email:s.email,csrf:s.csrf});}
